export default {
  idKey: 'id',
  cache: false,
  merge: true,
  replace: true,
  remote: false,
  listeners: {},
  prefixLocalId: 'ID_CREATED_LOCALLY___',
  showUpdatingProgress: true,
  updateLocalBeforeRemote: false,
  forceDelete: true,
  includeProperties: null,
  excludeProperties: null,
  insertDataBeforeCreateSuccess: false,
};
